blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://docs.etcswap.org
    about: Please review documentation to answer questions
  - name: List a token
    url: https://github.com/etcswap/tokens/issues/new
    about: Any requests to add a token to ETCswap should go here
